config/routes.rb
Amazon::Application.routes.draw do
  root :to => "homes#show"
  resource :home, :only => :show, :via => :get
  resource :admin, :only => :show, :via => :get
  resources :products, :only => [:create, :destroy, :show, :index, :edit, :update]
  resources :newsletter_requests, :only => :create
  resources :reminders, :only => [:create]
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/newsletter_request.rb
class NewsletterRequest < ActiveRecord::Base
  validates :email, uniqueness: true
  before_save :mailchimp_subscribe

  protected 
  def mailchimp_subscribe
    gb = Gibbon::API.new
    begin
      gb.lists.subscribe({:id => "be2fd96f18", :email => {:email => email}})
    rescue Exception => msg
      logger.info "Newsletter Request Failed with #{msg}"
      return false
    end
    return true
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope { order("featured DESC, created_at DESC")}
  has_many :reminders
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  def self.send_reminders
    #This is called via rake on a cron scheduler.
    ReminderMailer.send_list(reminders_to_send) 
  end

  private
  def self.reminders_to_send 
    self.select(:id).where("sent = FALSE AND date < ?", 8.days.from_now).map(&:id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :reminders

  def admin?
    self.email == "estsauver@gmail.com"
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authorize
  before_action :require_admin
  def show
    @product = Product.new
    @products = Product.all
  end

private
    def require_admin
      unless current_user.admin
        flash[:alert] = "Nothing to see here! Move along citizen."
        redirect_to root_path 
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_admin
    redirect_to root_path, status: 401 unless current_user and current_user.admin
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  #I'm unclear what the convention is for this case where the root is a singleton 
  #resource. Is there a way to make this less awkwardly connected. 
  def show
    @products = Product.all
    @product = @products.first
    render "products/show"
  end
end

app/controllers/newsletter_requests_controller.rb
class NewsletterRequestsController < ApplicationController
  def create
    @request = NewsletterRequest.new(newsletter_params)
    if @request.save
      flash[:success] = "Thanks for signing up!"
    else
      flash[:alert] = "Sorry, that email didn't look right. Did you mistype something?"
    end

    redirect_to(:back)
  end
  private 

  def newsletter_params
    params.require(:newsletter_request).permit(:email)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_admin, only: [ :create, :destroy, :edit, :update]
  def create
    @product = Product.new(product_params)
    @product.save
    flash[:alert] = "Product Created!"
    redirect_to admin_path
  end
  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Product Destroyed"
    redirect_to admin_path
  end

  def show
    @product = Product.find(params[:id])
    @products = Product.all
    respond_to do |format|
      format.html 
      format.json {render :json => @product}
    end
  end
  
  def index
    @products = Product.all
    respond_to do |format|
      format.json {render :json => @products}
    end
  end
  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to(@product)
    else
      render "edit"
    end
  end

  private
 
  def product_params
    params.require(:product).permit(:title, :description, :price, :rating, :image_url, :link)
  end

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController 
  before_action :redirect_visitors

  def create
    @reminder = current_user.reminders.create(reminder_params)
    if @reminder.save
      flash[:success] = "Reminder created!"
      redirect_to(:back)
    end
  end
  private
  def reminder_params
    puts params[:reminder][:date]
    params.require(:reminder).permit(:date, :event, :product_id)
  end

  def redirect_visitors
    if current_user 
      return true
    else
      flash[:notice] = "Please login or signup first!"
      redirect_to sign_up_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/show.html.erb
<h1> Admin Panel </h1>
<%= render partial: "products/form", locals: {product: @product} %>
<h2> Products</h2>
<%= render @products %>

app/views/homes/show.html.erb
<div class="row">
  <div class="large-9 push-3 columns">
    <div class="product featured panel">
      <div class="row">
        <div class="prdouct featured info large-6 columns">
          <div class="product featured title">
            <h2><%= @product.title %></h2>
          </div>
          <div class="product featured rating">
            <h5>Editors Rating: <%= @product.rating %></h5>
          </div>
          <div class="product featured price">
            <h6>Price: <%= @product.price %> $</h6>
          </div>
        </div><%# Ends Info block %> 
        <div class="product featured image large-4 columns">
          <%= image_tag( @product.image_url) %>
        </div>
      </div><%# Ends Row %>
      <div class="product featured description">
        <p><%= @product.description %></p>
      </div>
    </div><%# Ends Panel %>
  </div><%# Ends Featured Block %>
  <% cache @products do %>
    <div class="large-3 columns pull-9">
      <ul class="side-nav products">
        <% @products.each do |p| %>
          <li class="product<%= p.id == @product.id ? " active" : ""%>"><%= link_to p.title, p %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZenGifting</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width">
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="row">
    </div>
    <div class="row">
      <div class="large-8 columns">
        <div id="logo">
          <%= link_to root_path do %>
            <%= image_tag "logo.png" %>
          <% end %>
        </div>
      </div>
      <div class="large-4 columns text-right">
        <% if signed_in? %>
          <%= current_user.email %> 
          <%= link_to "Sign out" , sign_out_path, method: :delete%>
        <% else %> 
          <%= link_to "Sign in", sign_in_path %>
        <% end %>
      </div>
      <div class="large-12 columns">
        <% flash.each do |key, value| %>
          <div class="alert-box">
            <div class="flash <%= key %>"><%= value %></div>
            <a href="" class="close">&times;</a>
          </div>
        <% end %>
      </div>
    </div>
  </header>
  <%= yield %>
  <div class="large-12 columns topbar">
    <%= render "newsletter_requests/newsletter_request" %>
  </div>
</body>
</html>

app/views/newsletter_requests/_newsletter_request.html.erb
<div class="row email signup">
  <%= form_for :newsletter_request, url: newsletter_requests_path do |f| %>
    <div class="large-8 columns">
      <%= f.text_field :email, :placeholder=> "E mail", :class=> "inline"  %>
    </div>
    <div class="large-4 columns">
      <%= f.submit "Get our best weekly gift ideas!", :class=>"button secondary prefix" %>
    </div>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for product do |f| %>
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %> 

  <%= f.label :description, "Description" %> 
  <%= f.text_area :description %>

  <%= f.label :price %> 
  <%= f.text_field :price %>

  <%= f.label :rating %>
  <%= f.text_field :rating %>

  <%= f.label :image_url, "Image Url" %> 
  <%= f.text_field :image_url %>

  <%= f.label :link, "Amazon Link" %>
  <%= f.text_field :link %>

  <%= f.submit "Submit" %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
  <%= div_for product do %>
    <h3><%=link_to  product.title, "#" %> | <%= product.price %></h3>
    <p><%= product.description %></p>
    <%= link_to "Delete", product, method: :delete %>
    <%= link_to "Edit", edit_product_path(product), method: :get %>
  <% end %>
<% end %> 

app/views/products/edit.html.erb
<%= render partial: "form", locals: {product: @product} %>

app/views/products/show.html.erb
<% cache [@products, @product] do %>
  <div class="row">
    <div class="large-9 push-3 columns">
      <div class="product featured panel">
        <div class="row">
          <div class="prdouct featured info large-6 columns">
            <div class="product featured title">
              <h2><%= link_to @product.title, @product.link %></h2>
            </div>
            <div class="product featured rating">
              <h5>Editors Rating: <%= @product.rating %></h5>
            </div>
            <div class="product featured price">
              <h6>Price: <%= @product.price %> $</h6>
            </div>
          </div><%# Ends Info block %> 
          <div class="product featured image large-4 columns">
            <%= image_tag( @product.image_url) %>
          </div>
        </div><%# Ends Row %>
        <div class="product featured description">
          <p><%= simple_format(@product.description) %></p>
        </div>
        <fieldset>
        <div class="row">
          <div class="large-12 columns text-center">
            <h4> Get the perfect gift right before <%= image_tag "anyone_line.png" %>Birthday. </h4>
          </div>
        </div>
 
        <div class="row">
            <%= render  "reminders/form" %>
        </div>
        <div class="row text-center">
          <div class="large-12 columns"><h5> 
          We'll send you a reminder about a week before the big day with this product!
        </h5></div>
        </div>
      </fieldset>
      </div><%# Ends Panel %>

    </div><%# Ends Featured Block %>
    <div class="large-3 columns pull-9">
      <ul class="side-nav products">
        <% @products.each do |p| %>
          <li class="product<%= p.id == @product.id ? " active" : ""%>"><%= link_to p.title, p %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/reminders/_form.html.erb
<div class="row">
  <div class="large-12 columns">
  <%= form_for :reminder, url: reminders_path do |f|%>
    <div class="large-2 columns">
      <%= f.label :event, "Event", class: "inline" %>
    </div>
    <div class="large-4 columns">
      <%= f.text_field :event, placeholder: "Mother's Day", class: "inline"%>
    </div>
    <div class="large-3 columns">
      <%= f.date_field :date, :class => "inline", :placeholder => "05/11/2014" %>
    </div>
    <%= f.hidden_field :product_id, :value => @product.id %>

    <div class="large-3 columns">
      <%= f.submit "Add Reminder", class: "button prefix inline" %>
    </div>
  <% end %>
  </div>
</div>